name: Auto Merge Develop to Main

on:
  push:
    branches:
      - Develop  # Trigger action on push to Develop

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history for merge operations

      - name: Get last commit message on Develop
        id: last_commit
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $LAST_COMMIT_MSG"
          echo "commit_message=$LAST_COMMIT_MSG" >> $GITHUB_ENV

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Merge Develop into main (if commit message matches)
        run: |
          COMMIT_MSG_LOWER=$(echo "$commit_message" | tr '[:upper:]' '[:lower:]')

          if [[ "$COMMIT_MSG_LOWER" == *"ready to deploy"* ]]; then
            echo "Commit message matches, attempting merge."

            # Merge and detect conflicts
            if git merge origin/Develop --no-ff -m "Merge Develop into main"; then
              git push origin main
              echo "Merge successful, pushed to main."
            else
              echo "Merge conflicts detected. Stopping merge."
              git merge --abort
              exit 1
            fi
          else
            echo "Commit message does not match, skipping merge."
          fi
